import { MemeMoodFormValues } from "@/validators";

export const BUNCH_OF_MOODS: MemeMoodFormValues[] = [
    { label_en: "Happy", label_vi: "Vui vẻ", slug: "happy" },
    { label_en: "Sad", label_vi: "Buồn", slug: "sad" },
    { label_en: "Excited", label_vi: "Phấn khích", slug: "excited" },
    { label_en: "Tired", label_vi: "Mệt mỏi", slug: "tired" },
    { label_en: "Angry", label_vi: "Tức giận", slug: "angry" },
    { label_en: "Relaxed", label_vi: "Thư giãn", slug: "relaxed" },
    { label_en: "Anxious", label_vi: "Lo lắng", slug: "anxious" },
    { label_en: "Content", label_vi: "Hài lòng", slug: "content" },
    { label_en: "Bored", label_vi: "Chán", slug: "bored" },
    { label_en: "Surprised", label_vi: "Ngạc nhiên", slug: "surprised" },
    { label_en: "Confused", label_vi: "Bối rối", slug: "confused" },
    { label_en: "Proud", label_vi: "Tự hào", slug: "proud" },
    { label_en: "Scared", label_vi: "Sợ hãi", slug: "scared" },
    { label_en: "Calm", label_vi: "Bình tĩnh", slug: "calm" },
    { label_en: "Frustrated", label_vi: "Thất vọng", slug: "frustrated" },
    { label_en: "Peaceful", label_vi: "Bình yên", slug: "peaceful" },
    { label_en: "Energetic", label_vi: "Năng động", slug: "energetic" },
    { label_en: "Nostalgic", label_vi: "Hoài niệm", slug: "nostalgic" },
    { label_en: "Hopeful", label_vi: "Hy vọng", slug: "hopeful" },
    { label_en: "Disappointed", label_vi: "Thất vọng", slug: "disappointed" },
    { label_en: "Amused", label_vi: "Thích thú", slug: "amused" },
    { label_en: "Grateful", label_vi: "Biết ơn", slug: "grateful" },
    { label_en: "Embarrassed", label_vi: "Xấu hổ", slug: "embarrassed" },
    { label_en: "Confident", label_vi: "Tự tin", slug: "confident" },
    { label_en: "Overwhelmed", label_vi: "Quá tải", slug: "overwhelmed" },
    { label_en: "Inspired", label_vi: "Được truyền cảm hứng", slug: "inspired" },
    { label_en: "Jealous", label_vi: "Ghen tị", slug: "jealous" },
    { label_en: "Curious", label_vi: "Tò mò", slug: "curious" },
    { label_en: "Stressed", label_vi: "Căng thẳng", slug: "stressed" },
    { label_en: "Enthusiastic", label_vi: "Nhiệt tình", slug: "enthusiastic" },
    { label_en: "Lonely", label_vi: "Cô đơn", slug: "lonely" },
    { label_en: "Loved", label_vi: "Được yêu thương", slug: "loved" },
    { label_en: "Depressed", label_vi: "Trầm cảm", slug: "depressed" },
    { label_en: "Motivated", label_vi: "Có động lực", slug: "motivated" },
    { label_en: "Relieved", label_vi: "Nhẹ nhõm", slug: "relieved" },
    { label_en: "Cheerful", label_vi: "Vui tươi", slug: "cheerful" },
    { label_en: "Grumpy", label_vi: "Cáu kỉnh", slug: "grumpy" },
    { label_en: "Melancholic", label_vi: "Buồn bã", slug: "melancholic" },
    { label_en: "Optimistic", label_vi: "Lạc quan", slug: "optimistic" },
    { label_en: "Pessimistic", label_vi: "Bi quan", slug: "pessimistic" },
    { label_en: "Satisfied", label_vi: "Thỏa mãn", slug: "satisfied" },
    { label_en: "Shocked", label_vi: "Sốc", slug: "shocked" },
    { label_en: "Playful", label_vi: "Tinh nghịch", slug: "playful" },
    { label_en: "Serious", label_vi: "Nghiêm túc", slug: "serious" },
    { label_en: "Worried", label_vi: "Lo lắng", slug: "worried" },
    { label_en: "Ecstatic", label_vi: "Hân hoan", slug: "ecstatic" },
    { label_en: "Uncomfortable", label_vi: "Không thoải mái", slug: "uncomfortable" },
    { label_en: "Determined", label_vi: "Kiên quyết", slug: "determined" },
    { label_en: "Sympathetic", label_vi: "Thông cảm", slug: "sympathetic" },
    { label_en: "Indifferent", label_vi: "Thờ ơ", slug: "indifferent" }
]